sudo: required
services:
  - docker

before_install:
  - docker build -t tobsbola/docker-react -f Dockerfile.dev .

script:
  - docker run tobsbola/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReactTravisCi-env"
  bucket_name: "elasticbeanstalk-eu-west-2-844621846790"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"